// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "shop/internal/logic/admin"
	_ "shop/internal/logic/bizctx"
	_ "shop/internal/logic/data"
	_ "shop/internal/logic/login"
	_ "shop/internal/logic/middleware"
	_ "shop/internal/logic/order"
	_ "shop/internal/logic/permission"
	_ "shop/internal/logic/position"
	_ "shop/internal/logic/retation"
	_ "shop/internal/logic/role"
	_ "shop/internal/logic/session"
)
